http:
  port: 17000
  adminPort: 17001
  connectorType: nonblocking

elasticsearch:
  hosts:
  - localhost
  cluster: foxtrot

hbase:
  secure : false
  tableName: foxtrot

cluster:
  name: foxtrot
  disableMulticast: true
  members: []

logging:
  level: INFO
