elasticsearch:
  image: library/elasticsearch:1.7.3
  hostname: elasticsearch
  command: elasticsearch -Des.http.cors.enabled=true
  ports:
   - "9200:9200"
   - "9300:9300"

# hbase compose
hbase:
  image: hyness/hbase-rest-standalone
  hostname: hbase
  ports:
   - "2181:2181"
   - "8080:8080"
   - "16000:16000"
   - "16010:16010"
   - "16020:16020"
   - "16030:16030"
  volumes:
   - /data/hbase
   - /data/zookeeper

#enitity store compose
foxtrot-server:
  links:
   - elasticsearch
   - hbase
  container_name: foxtrot_server
  build: .
  ports:
   - "17000:17000"
   - "17001:17001"
  volumes:
   - /var/log/foxtrot-server
   # enviroment valiables
#  environment:
#   - ZK_CONNECTION_STRING=hbase:2181
