server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts:
  - ${ELASTICSEARCH_HOST}
  cluster: ${ELASTICSEARCH_CLUSTER_NAME}
  tableNamePrefix: ${ELASTICSEARCH_TABLE_NAME_PREFIX}
  port: ${ELASTICSEARCH_PORT}
  connectionType: ${ELASTICSEARCH_PROTOCOL}

hbase:
  secure : false
  tableName: ${HBASE_TABLE_NAME}
  hbaseZookeeperQuorum: ${HBASE_ZOOKEEPER_QUORUM}
  hbaseZookeeperClientPort: ${HBASE_ZOOKEEPER_CLIENT_PORT}

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_simple
    disableMulticast: true
    members: ["localhost:5701"]

cacheConfig:
  maxIdleSeconds: 15
  timeToLiveSeconds: 15

logging:
  level: INFO
  loggers:
    com.flipkart.foxtrot.core.querystore.actions: DEBUG
    org.apache.hadoop.hbase.zookeeper: WARN
    org.apache.zookeeper: WARN
    org.apache.hadoop.hbase.client: WARN
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

cardinality:
  enabled: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

deletionconfig:
  active: true
  interval: 86400
  initialdelay: 60

esIndexOptimizationConfig:
  active: true
  interval: 86400
  initialDelay: 6

consoleHistoryConfig:
  active: true
  interval: 86400
  initialDelay: 10

sessionCleanupConfig:
  active: true
  interval: 86400
  initialDelay: 10

auth:
  enabled: ${AUTH_ENABLED}
  jwt:
    issuerId: foxtrot-server
    privateKey: "6/Qh1eLvF7cGJEgH1wIMYErIpi0d8Kqt5wHKw/o5iFbhfziKiux03HfFihO2+f5FKpsjk1D7UmgdAWQsY966WkyAsyo22m4g+C+rNCwMUD/UM2qop7JZBDEkgWpwK8jpxOTpYUnaNsiBaBsadoZCQ+Ns/d8RrS7QPAW+1PETbdFfo+fPW0/Sm8RUmMKkc9jJ6bhuSpFH3q/bWoyPZnj7geYQQIkgmQv9jXaszw=="
    sessionDuration: 1h

  provider:
    type: OAUTH_GOOGLE
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    server: ${GOOGLE_CALLBACK_HOST_PORT}
    secureEndpoint: ${GOOGLE_SECURE_ENDPOINT}
