server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

logging:
  level: INFO
  loggers:
    com.flipkart.foxtrot: DEBUG
    org.apache.zookeeper: WARN
    org.apache.hadoop.hbase.zookeeper: WARN
    org.apache.hadoop.hbase.client: WARN

elasticsearch:
  hosts:
  - ${ELASTICSEARCH_HOST}
  cluster: ${ELASTICSEARCH_CLUSTER_NAME}
  tableNamePrefix: ${ELASTICSEARCH_TABLE_NAME_PREFIX}

hbase:
  secure : false
  tableName: ${HBASE_TABLE_NAME}
  hbaseZookeeperQuorum: ${HBASE_ZOOKEEPER_QUORUM}
  hbaseZookeeperClientPort: ${HBASE_ZOOKEEPER_CLIENT_PORT}

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_simple
    disableMulticast: true
    members: ["localhost:5701"]

cacheConfig:
  maxIdleSeconds: 15
  timeToLiveSeconds: 15

cardinality:
  enabled: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

deletionconfig:
  active: true
  interval: 86400
  initialdelay: 60

esIndexOptimizationConfig:
  active: true
  interval: 86400
  initialDelay: 6

consoleHistoryConfig:
  active: true
  interval: 86400
  initialDelay: 10

auth:
  disabled: false
  jwt:
    issuerId: foxtrot-server
    privateKey: "6/Qh1eLvF7cGJEgH1wIMYErIpi0d8Kqt5wHKw/o5iFbhfziKiux03HfFihO2+f5FKpsjk1D7UmgdAWQsY966WkyAsyo22m4g+C+rNCwMUD/UM2qop7JZBDEkgWpwK8jpxOTpYUnaNsiBaBsadoZCQ+Ns/d8RrS7QPAW+1PETbdFfo+fPW0/Sm8RUmMKkc9jJ6bhuSpFH3q/bWoyPZnj7geYQQIkgmQv9jXaszw=="
