server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts:
  - stg-els601.phonepe.nm2
  cluster: foxtrot
  tableNamePrefix: foxtrot
  getQueryTimeout: 10000

serviceDiscovery:
  namespace: local
  environment: local
  zookeeper: localhost:2181
  publishedHost: 127.0.0.1
  publishedPort: 8080

riemann:
  host: riemann-stage.local.int
  port: 5555
  prefix: local.foxtrot
  pollingInterval: 30
  tags:
    - foxtrot

hbase:
  secure: false
  tableName: foxtrot
  hbaseZookeeperQuorum: stg-dwhxenial002-stg-cloud005.phonepe.nm2:2181
  hbaseZookeeperClientPort: 2181
  seggregatedTablePrefix: foxtrot-
  hbaseZookeeperZnodeParent: /hbase-unsecure

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_simple
    disableMulticast: true
    members: ["localhost:5701"]

cacheConfig:
  maxIdleSeconds: 15
  timeToLiveSeconds: 15

logging:
  level: INFO

cardinality:
  enabled: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

elasticsearchTuningConfig:
  precisionThreshold: 500
  aggregationSize: 10000

esIndexOptimizationConfig:
  active: true
  interval: 86400
  initialDelay: 6

consoleHistoryConfig:
  active: true
  interval: 86400
  initialDelay: 10

deletionconfig:
  active: false
  interval: 86400
  initialdelay: 60

clusterRerouteConfig:
  active: false
  interval: 86400
  initialDelay: 10
  thresholdShardCountPercentage: 10

emailConfig:
  from: noreply@phonepe.com
  host: ops-jump001.phonepe.nm1
  port: 25
  user: AKIAJLCWHAOEDK4ZDOGQ
  password: AgjCxNI68hrnj6bIzuJCiZBlDXW+TioRoU11++Yx97
  url: /

gandalfConfig:
  httpConfig:
    usingZookeeper: false
    host: gandalf.traefik.stg.phonepe.com
    port: 80
    serviceName: gandalf
    environment: stage
    connections: 10
    idleTimeOutSeconds: 30
  authConfig:
    clientId: echo
    clientKey:  1234
    namespace:  echo
  permissionCacheConfig:
    ttlSeconds: 900
    enabled: true

primerBundleConfiguration:
  enabled: false
  authTypesEnabled:
    CONFIG: false
    ANNOTATION: true
  endpoint:
    type: simple
    host: primer.traefik.stg.phonepe.com
    port: 80
  cacheExpiry: 60
  cacheMaxSize: 100000
  clockSkew: 60
  prefix: Bearer
  privateKey: TwhjV5ujkvb41frpmqCve7ZfhqwSDMqOXe01DeDIsb2xCrW4bwfFnax9bi2uC9Kn

restrictAccess: false

gandalfConfiguration:
  serviceBaseUrl: "localhost:17000"
  username: "mudit.g@phonepe.com"
  password: "gandalf@echo"

elasticsearchTuningConfig:
  precisionThreshold: 500
  aggregationSize: 10000

swagger:
  resourcePackage: com.flipkart.foxtrot.server.resources
  title: Foxtrot
  description: A store abstraction and analytics system for real-time event data.
  uriPrefix: "/foxtrot"

distributedLockConfig:
  locksConfig:
    FUNNEL_APPROVAL:
      lockExpiryTimeInMs: 2000

funnelConfiguration:
  querySize: 100
  funnelIndex: foxtrot_funnel
  funnelConsoleUrl: http://siphon-ui.traefik.stg.phonepe.com/#/
  baseFunnelEventConfig:
    eventType: APP_LOADED
    category: APP_LOADED
  funnelDropdownConfig:
    eventTypes:
      - APP_LOADED
      - REFERRAL_RECEIVED
      - FORCE_LOGOUT
      - RESET_DEVICE_MAPPING
      - USER_LOGOUT
      - INSTALL_REFERRAL
      - P2P_SEND_TRANSACTION_TAG_SELECTED
      - P2P_SEND_TRANSACTION_CONTACT_CHANGE_INITIATED
      - P2P_REQUEST_TRANSACTION_INITIATED
      - P2P_REQUEST_CONTACT_SELECTED
      - P2P_REQUEST_TRANSACTION_TAG_SELECTED
      - P2P_REQUEST_TRANSACTION_CONTACT_CHANGE_INITIATED
      - P2P_SPLIT_TRANSACTION_INITIATED
      - P2P_SPLIT_CONTACT_SELECTED
      - P2P_SPLIT_TRANSACTION_TAG_SELECTED
      - P2P_SPLIT_TRANSACTION_CONTACT_CHANGE_INITIATED
      - P2P_INIT
      - MANAGE_REMINDER_INIT
      - WALLET_TOPUP_INIT
      - CHECK_BALANCE_INIT
      - P2P_CONTACT_SELECTED
    categories:
      - P2PSendTransaction
      - P2P_REQUEST_TRANSACTION
      - P2P_Split_Transaction
      - home
      - RechargePayment
      - DatacardPayment
      - Notifications
      - P2PPayToMoneyRequest
      - CS
      - Invite
      - SendMoney
      - ManageReminders
      - WalletTopup
      - CHECK_BALANCE
      - P2P
      - PAY
    deviceAttributes:
      - deviceId
      - Model
      - OS_Version
      - Network_Provider
      - Manufacturer
      - Latitude
      - Longitude
      - OS