http:
  port: 17000
  adminPort: 17001
  connectorType: nonblocking

elasticsearch:
  hosts:
  - 10.32.105.163
  cluster: prod-foxtrot-elasticsearch
  tableNamePrefix: foxtrot

hbase:
  secure : false
  tableName: foxtrot
  seggregatedTablePrefix: foxtrot-
  hbaseZookeeperQuorum: 10.33.37.208
  hbaseZookeeperClientPort: 2181

cluster:
  name: foxtrot
  disableMulticast: true
  members: ["localhost:5701", "localhost:5702"]

logging:
  level: INFO

deletionconfig:
  active: false
  interval: 86400
  initialdelay: 60