server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts:
  - localhost
  cluster: foxtrot
  tableNamePrefix: foxtrot

serviceDiscovery:
  namespace: phonepe
  environment: local
  zookeeper: stg-mesosm001.phonepe.int:2181
  publishedHost: 127.0.0.1
  publishedPort: 8080

riemann:
  host: riemann-stage.phonepe.int
  port: 5555
  prefix: phonepe.local.foxtrot
  pollingInterval: 30
  tags:
    - foxtrot

hbase:
  secure : false
  tableName: foxtrot
  hbaseZookeeperQuorum: localhost
  hbaseZookeeperClientPort: 2181

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_marathon
    endpoint: ${MARATHON_ENDPOINT}
    appId:  ${MARATHON_APP_ID}
    portIndex:  2

logging:
  level: INFO

deletionconfig:
  active: true
  interval: 86400
  initialdelay: 60
