server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts: localhost
  cluster: elasticsearch
  tableNamePrefix: foxtrot
  getQueryTimeout: 10000

serviceDiscovery:
  namespace: phonepe
  environment: local
  zookeeper: localhost:2181
  publishedHost: 127.0.0.1
  publishedPort: 8080

riemann:
  host: riemann-stage.phonepe.int
  port: 5555
  prefix: phonepe.local.foxtrot
  pollingInterval: 30
  tags:
    - foxtrot

hbase:
  secure : false
  tableName: foxtrot
  hbaseZookeeperQuorum: localhost
  hbaseZookeeperClientPort: 2181

cluster:
  name: foxtrot
  discovery:
    type: foxtrot_simple
    disableMulticast: true
    members: ["localhost:5701"]

logging:
  level: INFO

cardinality:
  cardinality: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

deletionconfig:
  active: false
  interval: 86400
  initialdelay: 60
